name: Lint and test with pip
on:
  workflow_call:
    inputs:
      sources-folder:
        required: false
        type: string
        default: 'src'
      base-folder:
        required: false
        type: string
        default: '.'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Black check
        uses: psf/black@stable
        with:
          options: '--check --verbose'
          src: ${{ inputs.base-folder }}/${{ inputs.sources-folder }}